# docker-compose.prod.yml (Production overrides)
services:
  vite:
    container_name: project-botany-vite
    restart: unless-stopped
    command: sh -c "yarn build && yarn start"
    networks:
      - fukaya-lab-network
    labels:
      caddy: project-botany.app.fukaya-sus.lab
      caddy.reverse_proxy: "{{upstreams 8080}}"
      caddy.tls: "internal"
    tty: true
    stdin_open: true

networks:
  fukaya-lab-network:
    external: true
    name: fukaya-lab-network
